services:
  node:
    volumes:
      - ./:/app
    build:
      dockerfile: ./Dockerfile
    environment:
      HELLO_WORLD: Cats!
    # If running a networked service (like ExpressJS), ports can be exposed here
    # ports:
    #   - 8081:8081
 
volumes:
  app:
